### ISSUE TITLE
Suggestions for more features(besides what I requested initially)

### ISSUE THREAD

**Issue by KingEdward9830** [rolandoislas/tree-spirit#1]
Hey, you can probably tell but I'm the same person who requested this mod to be made. One feature I'd like to be added would be the Infused Mushroom(or if you have a better name...) which would not only look fancy, but if it detects that it is placed inside of a room that is completely sealed in with Spirit Tree blocks(add a door that counts as a Spirit Tree block too, made from Logs and Essence), then it would cause the entire sealed-in area to become habitable for a tree spirit regardless of proximity to the blocks in question. (Similar to how Oxygen Sealers work in mods like Galacticraft or Advanced Rocketry, except the only "sealable" blocks are Spirit Tree materials(other than planks, because planks are dead and cannot support the tree spirit.)) Also, I noticed you were adding planks to the Spirit Wood, that is fine but they shouldn't be able to support the tree spirit in any way because as stated, they are dead. (They also shouldn't be affected by the breaking sequence for that reason.)
Moving on, after you have implemented everything in the request so far, maybe you should consider adding a few minor special abilities for tree spirits. (As in, players must have a tree or they can't use these items) An example would be a food item that acts like a Notch apple minus fire resistance(because why would something tree spirit-related give immunity to the tree spirit's main weakness?) for tree spirits only, acting as normal food or even poisoning a normal player. Crafted with a normal golden apple(not Notch) and a mixture of gold blocks and essence? I dunno, just seems like the Tree Spirit could use a little extra protection since they can't leave the tree ever. (and besides, crafting a normal golden apple and a few gold blocks is still a lot of gold for someone who can't mine very efficiently, thus making this recipe EXPENSIVE)

**Comment by opencma** [comment]
I am adding a list to easily view the pending features.

- [x] Custom tree(sapling. wood, leaves) & core
- [x] log decay if not in 1x1x1 (next to) radius of core or in range of a block chain that is connected
- [x] player death <--> core death
- [x] player/core death after 10 seconds \(configurable\) if the criteria for log decay is met
- [x] dimension/sub cores (boolean config option \[default: true\] - one per dimension per player)
- [x] custom grass type
- [x] add the 0x10x0 (10 above or below) block safe radius of the core to grass
    \(Currently the core enables this to allow tree growth.\)
- [x] recipes
- [x] essence from mob drops and leaves
- [x] sealed room/infused mushroom
- [x] tree spirit (player) specific utilities (e.g. food)
- [x] toggleable creative/spectator death countdown
- [x] Touch of Beacon API
- [x] fast elder sapling growth

**Comment by KingEdward9830** [comment]
Thanks, I will start testing it once the bare essentials of a survival-friendly mod (recipes and essence mainly) are added. (I don't like having to go into creative mode to start a survival world, especially when I requested this mod specifically so I wouldn't have to use command blocks to enforce this challenge.)

**Comment by KingEdward9830** [comment]
I notice you have checked off some stuff from that list, but you haven't committed to the repository or put out a new build yet. Do you intend to add everything on the list before next public update? If so that's perfectly fine, I just wondered. Also, I thought of one or two other little things. First, can there be a "hardcore challenge" config option that disables "tree spirit utilities" like the apple I mentioned? Also, one idea for a "tree spirit utility" which would be disabled by said config, would be a way to make crops grow faster. Perhaps by accelerating the tick rate for "crop" blocks slightly while a tree spirit player is standing nearby? This is mainly for early game, when players have no real source of food to help survive the first few nights.

**Comment by KingEdward9830** [comment]
One last suggestion. If you haven't already, can you make sure that players in Creative and Spectator game modes do not lose time on their "countdown" for when they're away from the tree? I ask this mainly because when you switch back to survival after having been in spectator/creative mode for various reasons, you shouldn't just die instantly.

**Comment by opencma** [comment]
There is a new build on CurseForge.

An Early game food enhancement was suggested in #2. I will look into soft-depending on [Touch of Beacon](https://minecraft.curseforge.com/projects/touch-of-beacon) to add the base tier beacon functionality to the core.

**Comment by KingEdward9830** [comment]
Also, can you make the Elder Sapling grow a bit faster? I planted one before midday of day one on a new survival world and it still hadn't grown when the sun was about to go down, remember not everyone kills a skeleton before the first night.
