### ISSUE TITLE
Multiplayer compatible?

### ISSUE THREAD

**Issue by BakarKadaienek** [rolandoislas/tree-spirit#16]
It seems this mod gives some issues when trying to use it on a server. Is this a bug, or is this mod just not compatible with multiplayer?

**Comment by opencma** [comment]
What issues have been encountered? Is there a crash report?

**Comment by LatimerCross** [comment]
Here are some crash reports with just the Tree spirit mod and Forge

[crash-2017-10-05_23.27.56-server.txt](https://github.com/rolandoislas/tree-spirit/files/1361532/crash-2017-10-05_23.27.56-server.txt)
[crash-2017-10-05_23.33.39-server.txt](https://github.com/rolandoislas/tree-spirit/files/1361531/crash-2017-10-05_23.33.39-server.txt)

**Comment by opencma** [comment]
It is a bug. I will try to get it sorted soon.

**Comment by BakarKadaienek** [comment]
Awesome, thanks! Our server can't run without it!

**Comment by LatimerCross** [comment]
Thanks for the quick update, but now we have a new crash. It does at least let a server load now.

[crash-2017-10-07_21.05.01-server.txt](https://github.com/rolandoislas/tree-spirit/files/1366574/crash-2017-10-07_21.05.01-server.txt)
