### ISSUE TITLE
Suggestions for the mod

### ISSUE THREAD

**Issue by LWnellA** [rolandoislas/tree-spirit#2]
Firstly, I will admit that i have not played the mod yet, but I have played the tree spirit challenge.

First, I think it'll be nice if, once separated from your tree, a bar will appear that'll count down(rather like the oxygen bar that appears when underwater) and instantly kill you when it runs out, but only when it runs out. This would prevent you from straying from your tree, but not punish you for say, being knocked off your tree by a skeleton or falling off while expanding or something. It'll also let wander a little ways off the tree to get something that's just out of reach.

Second, being near the heart log should slowly fill your hunger and/or health. At the start, it can be rather difficult to get food due to being unable to leave your tree, and you're often in the process of slowly dying while your tree is still young and small.

**Comment by opencma** [comment]
The countdown (not indicator) is available in the current alpha release. I'll push the commit for the indicator soon.

As for the food, I have another mod that adds that mechanic. https://minecraft.curseforge.com/projects/touch-of-beacon

![2017-03-03_00 19 59](https://cloud.githubusercontent.com/assets/6559115/23541894/558cd342-ffa7-11e6-8e3e-5cbfc3cf1407.png)
