### ISSUE TITLE
Was looking through creative mode, what is the difference between a normal and Elder core?

### ISSUE THREAD

**Issue by KingEdward9830** [rolandoislas/tree-spirit#3]
Just what the title says, what is the difference between a "Tree Spirit Core" and an "Elder Tree Spirit Core"? My best guesses are that it's a co-op feature or a Creative-only thing, but both of those are shots in the dark. Care to elaborate?

**Comment by opencma** [comment]
The normal core is just a result of reusing the sapling types to register core blocks. It has no use and does not spawn normally.
